# Day 3 Assignment

# Question 1: Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np
arr=np.arange(51)[2:51:3]
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Question 2:   Accept two lists of 5 elements each from the user Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [15]:
import numpy as np
list1=[]
list2=[]

print("Enter the elements of list1: ")

for i in range(0,5):                      #inputting elements of list1
    list1.append(int(input()))
    
print("Enter the elements of list2: ")    #inputting elements of list2  
for j in range(0,5):
    list2.append(int(input()))

print("The two lists entered are: ")
print(list1)
print(list2)                               #printing list1 and list2

arr1 = np.array(list1)                  
arr2 = np.array(list2)                     #converting list1 and list2 into np arrays

print("The np arrays are:  ")
print(arr1)
print(arr2)                                 #printing the np arrays

print("Concatenated two np arrays")
arr3 = np.append(arr1,arr2,axis=0)
print(arr3)

print("After sorting :")
print(np.sort(arr3))



Enter the elements of list1: 
5
1
3
4
2
Enter the elements of list2: 
7
0
8
9
6
The two lists entered are: 
[5, 1, 3, 4, 2]
[7, 0, 8, 9, 6]
The np arrays are:  
[5 1 3 4 2]
[7 0 8 9 6]
Concatenated two np arrays
[5 1 3 4 2 7 0 8 9 6]
After sorting :
[0 1 2 3 4 5 6 7 8 9]


# Question 3:  Write a code snippet to find the dimensions of a ndarray and its size.

In [22]:
import numpy as np
print("1D array ")
a1d = np.arange(10)
print(a1d)
print("The dimension is",a1d.ndim)
print("The size of the array is: ",a1d.size)

print("\n 2D array")
a2d = np.arange(12).reshape((3,4))
print(a2d)
print("The dimension is",a2d.ndim)
print("The size of the array is: ",a2d.size)


1D array 
[0 1 2 3 4 5 6 7 8 9]
The dimension is 1
The size of the array is:  10

 2D array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
The dimension is 2
The size of the array is:  12


# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet# 


In [26]:
import numpy as np
arr1d = np.arange(12)
print("1D array")
print(arr1d)

print("Convering into 2D array")
print(arr1d.reshape(3,4))


1D array
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Convering into 2D array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
